name: release

on:
  push:
    branches:
      - main

jobs:
  release-dogfood-to-pypi:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Publish to pypi
        uses: ./
        with:
          project-name: zora
          pypi-token: ${{ secrets.PYPI_TOKEN }}